//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCurrency
    {
        public int CyId { get; set; }
        public string CyCat { get; set; }
        public string symbol { get; set; }
        public string Descr { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
