//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFile
    {
        public int Id { get; set; }
        public string PNbr { get; set; }
        public string Ftype { get; set; }
        public Nullable<int> ModUserId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> Cdt { get; set; }
        public Nullable<System.DateTime> Udt { get; set; }
        public string FName { get; set; }
    }
}
