//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSupplier
    {
        public int Id { get; set; }
        public string EngName { get; set; }
        public string ChsName { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ModUserId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> Cdt { get; set; }
        public Nullable<System.DateTime> Udt { get; set; }
        public string SuppCat { get; set; }
        public string Rcpt_Bank_Nbr { get; set; }
        public string Rcpt_Bank_Name { get; set; }
        public string Contact { get; set; }
        public string QQ { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string type { get; set; }
    }
}
